

export interface Patient {
  PatientID: number;    // auto-generated by DB
  FirstName: string;
  LastName: string;
  Gender: string;
  DateOfBirth: string;  // YYYY-MM-DD
  PhoneNumber: string;
  CreatedAt: string;    // auto-generated by DB
  Age: number;          // computed by DB
}

